apiVersion: v2
name: spanner-etcd
description: etcd v3 API server backed by Google Cloud Spanner
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - etcd
  - spanner
  - kubernetes
  - storage
home: https://github.com/n0rm4l-me/spanner-etcd
sources:
  - https://github.com/n0rm4l-me/spanner-etcd
maintainers:
  - name: PaaS Team
