{{- if and .Values.auth.users (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spanner-etcd.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spanner-etcd.labels" . | nindent 4 }}
type: Opaque
stringData:
  users: {{ .Values.auth.users | quote }}
{{- end }}
