apiVersion: v1
kind: Service
metadata:
  name: {{ include "spanner-etcd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spanner-etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spanner-etcd.selectorLabels" . | nindent 4 }}
  ports:
    - name: etcd
      port: {{ .Values.service.port }}
      targetPort: etcd
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
