name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      spanner-emulator:
        image: gcr.io/cloud-spanner-emulator/emulator
        ports:
          - 9010:9010
          - 9020:9020

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: test
        run: go test ./... -timeout=120s -count=1
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
